

# TRIGGER DE ELIMINACION.
 USE PILDORAS;
 
CREATE TABLE PROD_ELIMINADOS(C_ART VARCHAR(25), NOMBRE VARCHAR(15), SECCION VARCHAR(15), PRECIO DECIMAL(10,2), 
PAIS_ORIGEN VARCHAR(20));


# CREAMOS EL TRIGGER.

CREATE TRIGGER ELIMPROD_AD AFTER DELETE ON PRODUCTOS FOR EACH ROW    #AD: AFTER DELETE POR NOMENCLATURA RECOMENDADA
INSERT INTO PROD_ELIMINADOS(C_ART, NOMBRE, SECCION, PRECIO, PAIS_ORIGEN)
                            VALUES(OLD.CÓDIGOARTÍCULO, OLD.NOMBREARTÍCULO, OLD.SECCIÓN, OLD.PRECIO, OLD.PAÍSDEORIGEN);


# AHORA VAMOS A ELIMANR UN REGISTRO DE LA TABLA DE PRODUCTOS.

DELETE FROM PRODUCTOS WHERE CÓDIGOARTÍCULO='AR40';

SET @@global.sql_mode= '';
# ME LANZABA UN "ERROR 1406: 1406: Datos demasiado largos para la columna" "NOMBRE" 
# AL REVISAR NOTE QUE MUCHOS DE LOS NOMBRES PASABA MAS DE 15 CARACTERES 
# LO MEJOR ERA CAMBIAR EL TIPO DE DATO DE VARCHAR(15) A VARCHAR(50)
#https://www.it-swarm-es.com/es/mysql/como-cambio-el-tipo-de-datos-para-una-columna-en-mysql/967055594/
alter table PROD_ELIMINADOS modify NOMBRE VARCHAR(50);


#AGREGAMOS 2 CAMPOS MÁS A LA TABLA...
alter table PROD_ELIMINADOS ADD COLUMN (USUARIO VARCHAR(50), FECHA_MODIF DATE);

# modificamos el trigger: P.D. No existe la órden de "alter trigger" y por lo que he podido indagar, 
#tampoco tienen idea de implementarlo en posteriores revisiones. Desde el Workbench lo puedes hacer, 
#pero si trabajas en modo texto... Olvídate, drop&create.

DROP TRIGGER IF EXISTS ELIMPROD_AD; # ELIMINAMOS EL TRIGGER 

# LO VOLVEMOS A CREAR, OJO NO ESTAMOS ELIMINANDO LA TABLA...

CREATE TRIGGER ELIMPROD_AD AFTER DELETE ON PRODUCTOS FOR EACH ROW  
INSERT INTO PROD_ELIMINADOS(C_ART, NOMBRE, SECCION, PRECIO, PAIS_ORIGEN, USUARIO, FECHA_MODIF)
		VALUES(OLD.CÓDIGOARTÍCULO, OLD.NOMBREARTÍCULO, OLD.SECCIÓN, OLD.PRECIO, OLD.PAÍSDEORIGEN, current_user(), now());





































